Repository facebookexperimental/Robyn, pull requests merged in 2023-04, with the labels that each got.

#687 feat: reduce object sizes up to 87%
  R/DESCRIPTION
  R/R/model.R
  R/R/outputs.R
  R/R/pareto.R
  R/R/transformation.R
  demo/demo.R
Labels: enhancement, CLA Signed

#680 feat: RSSD penalty for 0 media effects media (parameter)
  R/R/model.R
  R/README.md
  R/man/robyn_mmm.Rd
  R/man/robyn_run.Rd
  R/man/robyn_train.Rd
Labels: CLA Signed

#708 Respect plot_folder value on robyn_refresh
  R/R/refresh.R
Labels: bug, CLA Signed

#686 feat: always constraint prophet coefs to 0-1
  R/R/model.R
Labels: CLA Signed
